config/routes.rb
 Rails.application.routes.draw do
   resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    # Defines the root path route ("/")
  # root "articles#index"
  put 'posts/:id/toggle_complete', to: 'posts#toggle_complete', as: 'toggle_complete'
  get "about", to: "pages#about"
  get "dashboard", to: "lessons#dashboard"
  get "show_lessons", to: "lessons#show_lessons"
  authenticated :user do
     root to: 'lessons#dashboard', as: :authenticated_root
  end
  root "pages#home"
  resources :posts
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  def show_lessons
    @lessons = lessons_by_user
  end

  def dashboard
    @lessons = lessons_by_user
    @post = Post.all
    @completed_lessons = count_finished_lessons
    @ongoing_lessons = count_ongoing_lessons
  end

  def count_ongoing_lessons
    lesson = lessons_by_user
    count = 0
    lesson.each do |lesson|
      if lesson.is_completed == false
        count += 1
      end
    end
    return count
  end
  def count_finished_lessons
    lesson = lessons_by_user
    count = 0
    lesson.each do |lesson|
      if lesson.is_completed == true 
        count += 1
      end
    end
    return count
  end

  def count_ongoing_lessons
    lesson = lessons_by_user
    count = 0
    lesson.each do |lesson|
      if lesson.is_completed == false 
        count += 1
      end
    end
    return count

  end

  def lessons_by_user
    lessons = Lesson.all 
    lessons.select do |lesson|
    lesson.user_id == current_user.id
    end
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:id, :number, :user_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Id:</strong>
    <%= lesson.id %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= lesson.number %>
  </p>

  <p>
    <strong>User:</strong>
    <%= lesson.user_id %>
  </p>

</div>

app/views/lessons/_user_lesson.html.erb
<div id="<%= dom_id lesson %>" class="dashboard_lesson">
    <%post = Post.find_by(id: lesson.number)%>
        <%if lesson.is_completed == true%>
            <div id="posts" class="lesson" data-status="finished">
                <div class="category">
                <h2> <%= post.title%> </h2>
                 <p> Status:  Completed </p>
                <%= link_to "Show this Lesson", post%>
                </div>
            </div>
        <%else%>
            <div id="posts" class="lesson" data-status="ongoing">
                <div class="category">
                <h2> <%= post.title%> </h2>
                <p> Status:  Ongoing </p>
                <%= link_to "Show this Lesson", post%>
                </div>
            </div>
        <%end%>
</div>

app/views/lessons/dashboard.html.erb
 <head>
 <%= stylesheet_link_tag "dashboard.css"%>
 <%= javascript_import_module_tag "script"%>
 </head>
 <div class="dashboard">
        <section class="navigation">
            <ul>
            </ul>
            <div id="nav-content">
                <p><%= link_to current_user.name.capitalize, dashboard_path, class:"link-text", id:"username"%> </p>
               <p> <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"link-text" %> </p>
               <!-- <img src="asset/images/001-quiz.png" alt="quiz" class="icons"> *optional kung lalagyan ng quizzes*-->
            </div>

        </section>
        
        <section class="main">
            <section class="main"><!-- Main -->
    
    
  <div class="title">
            <h1>My Lessons</h1>

        </div>

        <div class="lesson_list"> 
        <!--lesson list-->
        <% @lessons.each do |lesson|%>
        <%post = Post.find_by(id: lesson.number)%>
        <%= render partial:"user_lesson", locals: {lesson: lesson, post: post}%>
        <%end%>
        </div> <!--lesson list end-->
        </section>

        <section class="secondary"> <!--Secondary-->
            <div class="chart">
                <h2>Total Lessons</h2>
                <div>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </div>
                <div class="complete">
                    <p>From <%=pluralize(@post.length, "project")%> 

                    </p>
                </div>
            </div>
            <div class="recent_project"> <!--recent proj-->
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Finished: <p id="finished"><%=@completed_lessons%></p></h2>
                            <h2>ongoing: <p id="ongoing"><%=@ongoing_lessons%></p></h2>
                        </div>  
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Remaining</h2>
                        </div> 
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>ongoing</h2>
                        </div>
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Stalled</h2>
                        </div>
                    </div>
                </div>
            </div> <!--recent proj end-->
        </section>
    </div>

    <%= javascript_importmap_tags %>
    <!--Chart-->
    <script src= "asset/js/script.js">
 
    </script>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lessons</h1>

<div id="lessons">
  <% @lessons.each do |lesson| %>
    <%= render lesson %>
    <p>
      <%= link_to "Show this lesson", lesson %>
    </p>
  <% end %>
</div>

<%= link_to "New lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lesson %>

<div>
  <%= link_to "Edit this lesson", edit_lesson_path(@lesson) %> |
  <%= link_to "Back to lessons", lessons_path %>

  <%= button_to "Destroy this lesson", @lesson, method: :delete %>
</div>

app/views/lessons/show_lessons.html.erb
<% @lessons.each do |lesson|%>
<%post = Post.find_by(id: lesson.number)%>
<%= render partial:"user_lesson", locals: {lesson: lesson, post: post}%>
 <%end%>