config/routes.rb
 Rails.application.routes.draw do
   resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    # Defines the root path route ("/")
  # root "articles#index"
  put 'posts/:id/toggle_complete', to: 'posts#toggle_complete', as: 'toggle_complete'
  get "about", to: "pages#about"
  get "dashboard", to: "lessons#dashboard"
  get "show_lessons", to: "lessons#show_lessons"
  authenticated :user do
     root to: 'lessons#dashboard', as: :authenticated_root
  end
  root "pages#home"
  resources :posts
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def dashboard
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
     @post = Post.find(params[:id])
     @lesson = find_current_lesson
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def toggle_complete
    @lesson = find_current_lesson
    @lesson.is_completed = !@lesson.is_completed
    @lesson.save
    post = Post.find(params[:id])
    redirect_to post_path(post)
  end

  def find_current_lesson
    current_post = Post.find(params[:id])
    lessons = lessons_by_user
    lessons.each do |lesson|
      if current_post.id == lesson.number
        return lesson
      end
    end
  end

  def lessons_by_user
      lessons = Lesson.all 
      lessons.select do |lesson|
        lesson.user_id == current_user.id
      end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_dashboard.html.erb
<div id="posts" class="lesson" data-status="finished">
                <div class="category">
                    <% @posts.each do |post|%>
                    <h2><%= post.title %> </h2>
                    <%current_lesson = Lesson.find_by(user_id: current_user.id)%>
                    <%if current_lesson.number == post.id%>
                        <%if current_lesson.is_completed == true%>
                            <p> Status:  Completed </p>
                        <%else%>
                            <p> Status: Ongoing </p>
                        <%end%>
                    <%end%>
                <% end %>

                </div>
</div><!--proj 1-->

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, size: "70x100" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<head>
<%= stylesheet_link_tag "post.css" %>
</head>
<link href='https://unpkg.com/css.gg@2.0.0/icons/css/check.css' rel='stylesheet'>
<body>
<div class="main">
<div class= "sidebar">
    <ul> 
    <%if current_user%>
    <li> <%= link_to current_user.name.capitalize, dashboard_path, id:"user-name"%></li>
    <%end%>
    <li><a href="#" class="active"> 
    <!---<span class= "icon">  <%= image_tag("dashboards.png", class:"dashboard", alt:"Dashboard")%> </span>---->
    <span class= "item"><%= link_to "Dashboard", dashboard_path %></span> </a></li>

    <li><a href="#">
    <!---<span class= "icon">  <%= image_tag("sign_out.png", class:"signout", alt:"open_door")%> </span>---->
    <span class= "item"> <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete} %></span></a></li>
    </ul>

</div>

  <div id="<%= dom_id post %>" class="content">
    <h1 class= "tittleh1">
    <%= post.title %></h1>
    <% if post.id == 3 %>
    <%= image_tag "dingdong.jpg" %>
    <% end %>
    <p>  <%=simple_format(post.body)%> </p>
    <%if @lesson.is_completed == true %>
    <i class="gg-check"></i>
    <%= button_to "Lesson Completed", toggle_complete_path, method: :put, id:"complete_button"%>
    <% else %>
    <%= button_to "Mark Complete", toggle_complete_path, method: :put, id:"complete_button"%>
    <% end %>
  </div>
</div>
</body>
<%= javascript_import_module_tag "script" %>

app/views/posts/dashboard.html.erb
 <head>
 <%= stylesheet_link_tag "dashboard.css"%>
 <%= javascript_import_module_tag "script"%>
 </head>
 <div class="dashboard">
        <section class="navigation">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete%>
            <%= image_tag("Logopng.png", alt:"Code Verse Hub", class:"dashboard-logo")%>
            <div>
                <%= image_tag("dashboard_icon.png", alt:"dashboard", class:"icons")%>
                <%= image_tag("lesson_icon.png", alt:"lesson", class:"icons")%>
                <%= image_tag("settings_icon.png", alt:"settings", class:"icons")%>
               <!-- <img src="asset/images/001-quiz.png" alt="quiz" class="icons"> *optional kung lalagyan ng quizzes*-->
            </div>
            <%= image_tag("User_Avatar.png", alt:"user image", class:"user")%>

        </section>
        
        <section class="main">
            <section class="main"><!-- Main -->
    
    
  <div class="title">
            <h1>My Lessons</h1>

        </div>

        <div class="lesson_list"> <!--lesson list-->
            <%=render 'dashboard'%>
            <div class="lesson" data-status="finished" title="Finished lesson"> <!--proj 1-->  
                <div class="category">
                    <h2>Exp topic</h2><!--edit this para sa content or topic-->
                    <p>status of lesson</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                   
                    <ul class="activity">
                        <li>example </li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 1-->

            <div class="lesson" data-status="ongoing" title="Ongoing lesson"> <!--proj 2-->
                <div class="category">
                    <h2>wally</h2><!--edit this para sa content or topic-->
                    <p>Active recently</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                    
                    <ul class="activity">
                        <li> may blod</li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 2-->

            <div class="lesson" data-status="ongoing" title="Ongoing lesson"> <!--proj 3-->
                <div class="category">
                    <h2> love story</h2><!--edit this para sa content or topic-->
                    <p>ongoing</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                    <ul class="activity">
                        <li> jeff loves kristine</li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 3-->

            <div class="lesson" data-status="finished" title="Finished lesson"> <!--proj 4-->
                <div class="category">
                    <h2> Topic 4</h2><!--edit this para sa content or topic-->
                    <p>Paulol</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                    <ul class="activity">
                        <li> erwin skincare tutorial</li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 4-->

            <div class="lesson" data-status="ongoing" title="Ongoing lesson"> <!--proj 5-->
                <div class="category">
                    <h2> Topic 5</h2><!--edit this para sa content or topic-->
                    <p>bentahan ng shabu</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                    <ul class="activity">
                        <li> turuan kayo ni carlos mag abot</li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 5-->

            <div class="lesson" data-status="stalled" title="Stalled lesson"> <!--proj 6-->
                <div class="category">
                    <h2> Topic 6</h2><!--edit this para sa content or topic-->
                    <p>pano mag pauwi ng lasing</p><!-- ikaw bahala kung mag lalagay kapa dito or burahin-->
                    <ul class="activity">
                        <li> tutorial by gen</li><!--pwede ka mag lagay ng kung ano matuturo sa topic dito-->
                    </ul>
                </div>
            </div><!--proj 6-->

        </div> <!--lesson list end-->
        </section>

        <section class="secondary"> <!--Secondary-->
            <div class="chart">
                <h2>Total Lessons</h2>
                <div>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </div>
                <div class="complete">
                    <h3>Completed</h3>
                    <p>From 5 projects
                    </p>
                </div>
            </div>
            <div class="recent_project"> <!--recent proj-->
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Finished</h2>
                        </div>  
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Remaining</h2>
                        </div> 
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>ongoing</h2>
                        </div>
                    </div>
                </div>
                <div class="listing">
                    <div class="tittle">
                        <div class="category">
                            <h2>Stalled</h2>
                        </div>
                    </div>
                </div>
            </div> <!--recent proj end-->
        </section>
    </div>

    <%= javascript_importmap_tags %>
    <!--Chart-->
    <script src= "asset/js/script.js">
 
    </script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<div id="admin_edit">
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>